### ISSUE TITLE
Guidance request

### ISSUE THREAD

**Issue by josephKhoury95** [stanford-esrg/lzr#1]
Hello,

Just for clarification; I just want to know if I have to choose one random IP address for the `$source-ip` variable when executing the make command.

Also, I am having the below problem when doing the scan. What could it be?
>  panic: ens8: No such device exists (SIOCGIFHWADDR: No such device)

Can you please offer some guidance on the above concerns? 
Thank you in advance.

**Comment by LizIzhikevich** [comment]
Hi!

`$source-ip` is the IP address of the machine you plan to scan from. 

I have added a feature to fix the panic error: you can now specify the network interface (e.g., "eth0") your machine will use to send packets over using the -sendInterface flag when running lzr (e.g., -sendInterface eth0 ) . You can run the `ifconfig` command to check the names of the network interfaces your machine uses.

**Comment by josephKhoury95** [comment]
Thank you, this was helpful.
