### ISSUE TITLE
Unable to build from source (iptables issue)

### ISSUE THREAD

**Issue by somu1795** [stanford-esrg/lzr#11]
As of go1.17 the go get command mentioned doesn't work and has been deprecated, instead go suggests to use go install, which fails.  
When I'm trying to build from source I encounter this issue:
```bash
$ make all source-ip=256.256.256.256/32
sudo iptables -A OUTPUT -p tcp --tcp-flags RST RST -s 256.256.256.256/32 -j DROP
iptables v1.8.7 (legacy): host/network `256.256.256.256' not found
Try `iptables -h' or 'iptables --help' for more information.
make: *** [Makefile:10: all] Error 2
```
OS: fedora 36

**Comment by LizIzhikevich** [comment]
The error is coming from iptables. It is complaining that you are inputting an invalid ip address to scan from. The program expects you to provide a valid source ip address that the scanner will scan from.
