### ISSUE TITLE
LZR Continously Crashing

### ISSUE THREAD

**Issue by rek7** [stanford-esrg/lzr#15]
The following command: `zmap 0.0.0.0/0 -p 80,443 --shards=32 --shard=3 --seed=123 -B 10m --probe-ttl=510 -O json -f saddr,daddr,sport,dport,seqnum,acknum,window,ttl --sender-threads=16 --source-ip=xxx --output-filter "success=1 && repeat=0"  | ztee -u zmap_status.txt -l zmap_errors.txt --raw ztee.output | lzr --handshakes http,tls -t 5 -w 3 -sendInterface eth0 -gatewayMac xxx -f -`

Results in the following crash after a few minutes. This is an issue that has occurred on numerous servers. Could this be patched to handle this issue gracefully, or are there any workarounds I could use to make this tool usable?
```
panic: send: No buffer space available

goroutine 58 [running]:
github.com/stanford-esrg/lzr.SendSyn(0xc29dd87c00, 0xc00011c1e0, 0xc000063ea8?)
        /tmp/lzr/handle_syn.go:31 +0x156
github.com/stanford-esrg/lzr.handleExpired(0xc00015e0e0, 0xc29dd87c00, 0xc00011c1e0, 0xc000128358?, 0xf?)
        /tmp/lzr/handle_expired.go:77 +0x19e
github.com/stanford-esrg/lzr.HandleTimeout(0xc00015e0e0, 0xc29dd87c00, 0x0?, 0xc29dd87c00?, 0x0?, 0x0?)
        /tmp/lzr/handle_timeout.go:52 +0x185
github.com/stanford-esrg/lzr/bin.LZRMain.func4(0x0?)
        /tmp/lzr/bin/bin.go:162 +0xc7
created by github.com/stanford-esrg/lzr/bin.LZRMain in goroutine 1
        /tmp/lzr/bin/bin.go:149 +0x734
```

I've also tried increasing the tcp_mem, wmem max, and xfrm4_gc_thresh:

```
echo "$(($RAM * 1024 * 1024 / 4096)) $(($RAM * 1024 * 1024 * 2 / 4096)) $(($RAM * 1024 * 1024 * 3 / 4096))" > /proc/sys/net/ipv4/tcp_mem
sysctl net.ipv4.xfrm4_gc_thresh=65536
echo 83886080 > /proc/sys/net/core/wmem_max
echo 83886080 > /proc/sys/net/core/wmem_default
echo 83886080 > /proc/sys/net/core/rmem_max
echo 83886080 > /proc/sys/net/core/rmem_default
``` 

However, this doesn't work. I've only had this issue with this tool. Other ones like Zmap, zrgab2, and masscan never crash and throw this error.

**Comment by rek7** [comment]
Also, lzr is throwing almost a 90% false negative rate. Something is wrong. However, I've tried this on other providers and a bare metal setup with similar results.

**Comment by LizIzhikevich** [comment]
Hi Raphael, Can you try changing the number workers "w" to 1000 instead of "3". Although this might not solve the problem, I imagine that just allowing LZR to use 3 threads would dramatically slow it down, causing a lot of back up.

**Comment by rek7** [comment]
Even after adding the additional workers, its crashing with:

```
panic: send: No buffer space available

goroutine 3241 [running]:
github.com/stanford-esrg/lzr.SendSyn(0xc29d19e700, 0xc0000121f8, 0xc29d87dea8?)
        /tmp/lzr/handle_syn.go:31 +0x156
github.com/stanford-esrg/lzr.handleExpired(0xc0000e6000, 0xc29d19e700, 0xc0000121f8, 0xc11e6501d8?, 0x10?)
        /tmp/lzr/handle_expired.go:77 +0x19e
github.com/stanford-esrg/lzr.HandleTimeout(0xc0000e6000, 0xc29d19e700, 0x0?, 0xc29d19e700?, 0x0?, 0x0?)
        /tmp/lzr/handle_timeout.go:52 +0x185
github.com/stanford-esrg/lzr/bin.LZRMain.func4(0x0?)
        /tmp/lzr/bin/bin.go:162 +0xc7
created by github.com/stanford-esrg/lzr/bin.LZRMain in goroutine 1
        /tmp/lzr/bin/bin.go:149 +0x734
panic: send: o buffer space available

goroutine 4035 [running]:
github.com/stanford-esrg/lzr.SendSyn(0xc29d180c40, 0xc0000121f8, 0xc29cd6aea8?)
        /tmp/lzr/handle_syn.go:31 +0x156
github.com/stanford-esrg/lzr.handleExpired(0xc0000e6000, 0xc29d180c40, 0xc0000121f8, 0xc11e6501d8?, 0x10?)
        /tmp/lzr/handle_expired.go:77 +0x19e
github.com/stanford-esrg/lzr.HandleTimeout(0xc0000e6000, 0xc29d180c40, 0x0?, 0xc29d180c40?, 0x0?, 0x0?)
        /tmp/lzr/handle_timeout.go:52 +0x185
github.com/stanford-esrg/lzr/bin.LZRMain.func4(0x0?)
        /tmp/lzr/bin/bin.go:162 +0xc7
created by github.com/stanford-esrg/lzr/bin.LZRMain in goroutine 1
        /tmp/lzr/bin/bin.go:149 +0x734
panic: send: No buffer space available

goroutine 3154 [running]:
github.com/stanford-esrg/lzr.SendSyn(0xc29d181180, 0xc0000121f8, 0xc29d868ea8?)
        /tmp/lzr/handle_syn.go:31 +0x156
github.com/stanford-esrg/lzr.handleExpired(0xc0000e6000, 0xc29d181180, 0xc0000121f8, 0xc11e6501d8?, 0x10?)
        /tmp/lzr/handle_expired.go:77 +0x19e
github.com/stanford-esrg/lzr.HandleTimeout(0xc0000e6000, 0xc29d181180, 0x0?, 0xc29d181180?, 0x0?, 0x0?)
        /tmp/lzr/handle_timeout.go:52 +0x185
github.com/stanford-esrg/lzr/bin.LZRMain.func4(0x0?)
        /tmp/lzr/bin/bin.go:162 +0xc7
created by github.com/stanford-esrg/lzr/bin.LZRMain in goroutine 1
        /tmp/lzr/bin/bin.go:149 +0x734
```

**Comment by LizIzhikevich** [comment]
What is the RAM available on your machine?

If you scan only a couple IP addresses, can you look at the tcpdump and see if at the packet level LZR seems to be operating as expected? 

Can you try slowing down the ZMap scan substantially and see if that helps?

Also did you run the command that gets outputted when `make` ing LZR (to make sure the kernel doesn't RST the connections opened by zmap)

**Comment by rek7** [comment]
8gb of ram, I also did the IP tables command with the external IP of the vpc / setup. it seems like the packet is the same. do you want me to do a raw tcpdump and send the results over?

**Comment by LizIzhikevich** [comment]
Can you first re-run lzr while monitoring your RAM and see how much of your RAM is used right before LZR throws the error? I.e., is the out of memory due to RAM running out, or due to internal LZR memory running out

**Comment by rek7** [comment]
looks to be using a little over half still 2-3 gb free at any time. i think its because zmap is taking up all the sockets, is there a way to get lzr to buffer automatically or not panic based on the amount of connections?

**Comment by TheDr1ver** [comment]
I just wanted to clarify, I'm working the same problem/project with @rek7 and if I omit the workers and threads args from LZR I don't have any issues with the command he posted (as long as the MAC matches the gateway).

If you're trying to recreate the issue that might help troubleshoot.

**Comment by TheDr1ver** [comment]
From my standpoint, I think you can feel free to close this issue. 

@rek7 can correct me if he feels strongly to the contrary, but I'm about.. 75?% sure the problem lies within either starting the `zmap|ztee|lzr|ztee|zgrab2` pipeline too early in the cloud-image-startup process, or not segregating the launch commands properly from the pulumi cloud-init script we were initially trying to use.

Once I set it to 3 separate commands of :

```
launch instance/install image, 
after that's finished, wait 30+ seconds,
after that's finished, launch the zmap|lzr|zgrab2 scan pipeline via remote SSH cmd
```

I've seen very few (if any) errors.

**Comment by LizIzhikevich** [comment]
Thank you for the follow-up! I will close for now.
