### ISSUE TITLE
destination mac address hardcoded in source code for outbound packets

### ISSUE THREAD

**Issue by lgrangeia** [stanford-esrg/lzr#2]
It seems like there is a mac address hardcoded in `construct_responses.go` :

```
func getHostMacAddr() (addr net.HardwareAddr) {
	return net.HardwareAddr{0xa8, 0x1e, 0x84, 0xce, 0x64, 0x5f}
}
```
This makes it difficult for the packets to actually arrive to their destination unless the scanning machine's gateway's mac address matches this address.

**Comment by LizIzhikevich** [comment]
Thank you for pointing this out.

I have now added a " -gatewayMac " flag for users to specify their desired gateway. If no gateway is specified, lzr can now also infer the Mac address by parsing incoming traffic.

**Comment by lgrangeia** [comment]
Great, thank you!
