### ISSUE TITLE
Issues with ZMap+LZR

### ISSUE THREAD

**Issue by arsarabi** [stanford-esrg/lzr#5]
Hello,

I've run into the following issues when using LZR with ZMap.

- When reading SYN-ACKs from ZMap, the SYN and ACK flags are not explicitly set. This causes LZR to respond to SYN-ACKs with a zero window size (which shouldn't happen according to the algorithm diagram), since the ``windowZero`` function checks for those flags.
- ZMap outputs SeqNum and AckNum as signed 32-bit integers, but LZR uses 64-bit integers on a 64-bit machine  (int is architecture-dependent in Go). This causes verification to fail for the first handshake whenever the MSB in SeqNum or AckNum is one.

Here is a possible fix, though the fix for the latter is a bit hacky!

```diff
--- a/packet.go
+++ b/packet.go
@@ -132,7 +132,17 @@ func convertFromZMapToPacket( input string ) *packet_metadata      {
        synack := &packet_metadata{}
        //expecting ip,sequence number, acknumber,windowsize, sport, dport
        err := json.Unmarshal( []byte(input),synack )
+       synack.SYN = true
+       synack.ACK = true
        synack.Processing = true
+       if strconv.IntSize == 64 {
+               if synack.Seqnum < 0 {
+                       synack.Seqnum = 4294967296 + synack.Seqnum
+               }
+               if synack.Acknum < 0 {
+                       synack.Acknum = 4294967296 + synack.Acknum
+               }
+       }
        if err != nil {
                log.Fatal(err)
                return nil
```

**Comment by LizIzhikevich** [comment]
Hey, 

Good catch with the flags not being set when reading from zmap. If running 2 handshakes - the zero windows would have been caught, but yes the flags should be set regardless. I have pushed the fix. 

With regards to ZMap returning signed integers, can you actually file an issue with zmap? If this is in fact what is going on, then I'd rather they fix it then try to work-around ZMap's bugs in LZR.
